### ISSUE TITLE
Slots removal crashes samkilla

### ISSUE THREAD

**Issue by Psychokiller1888** [project-alice-powered-by-snips/ProjectAlice#38]
Removing a slot from a dialog template such as deprecated ones or unused ones, crashes Samkilla with the following error:

```
[Safe] Handle error gracefully
<class 'KeyError'>
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/snips/samkilla/processors/IntentRemoteProcessor.py", line 107, in syncIntentsOnAssistantSafely
    return self.syncIntentsOnAssistant(typeEntityMatching=typeEntityMatching, skillId=skillId, intentSyncState=intentSyncState, hashComputationOnly=hashComputationOnly)
  File "/home/pi/ProjectAlice/core/snips/samkilla/processors/IntentRemoteProcessor.py", line 122, in syncIntentsOnAssistant
    intentMatching = self.syncIntent(typeEntityMatching, skillId, hashComputationOnly)
  File "/home/pi/ProjectAlice/core/snips/samkilla/processors/IntentRemoteProcessor.py", line 82, in syncIntent
    language=self._intentLanguage
  File "/home/pi/ProjectAlice/core/snips/samkilla/Intent.py", line 226, in edit
    structuredSlots, entities = self.formatSlotsAndEntities(typeEntityMatching, slotsDefinition)
  File "/home/pi/ProjectAlice/core/snips/samkilla/Intent.py", line 276, in formatSlotsAndEntities
    slotEntityId = slot['type'] if snipsSpecialSlot else typeEntityMatching[slot['type']]['entityId']
KeyError: 'More'
```

**Comment by Psychokiller1888** [comment]
Top priority, this happens all the time and will happen all the time as modules get updated and new modules are created

**Comment by jr-k** [comment]
Fixed on alpha2
