### ISSUE TITLE
An unhandled exception occured, Alice fails to run

### ISSUE THREAD

**Issue by mjlill** [project-alice-powered-by-snips/ProjectAlice#74]
```
- Traceback: Traceback (most recent call last):
  File "main.py", line 90, in <module>
    main()
  File "main.py", line 76, in main
    projectAlice = ProjectAlice()
  File "/home/pi/ProjectAlice/core/ProjectAlice.py", line 17, in __init__
    self._superManager.onStart()
  File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 80, in onStart
    talkManager.onStart()
  File "/home/pi/ProjectAlice/core/voice/TalkManager.py", line 25, in onStart
    self.loadTalks()
  File "/home/pi/ProjectAlice/core/voice/TalkManager.py", line 46, in loadTalks
    for langTalkFile in langTalksMountpoint.iterdir():
  File "/usr/local/lib/python3.7/pathlib.py", line 1090, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: 'modules/AliceCore/talks'
```

**Comment by Psychokiller1888** [comment]
Updating to alpha 2 deleted your modules in modules directory. Start a download procedure for them all
